version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bill
    volumes:
      - ./db-data:/var/lib/postgresql/data
